//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> iscomplete { get; set; }
        public Nullable<System.DateTime> completedat { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedat { get; set; }
        public string deletedby { get; set; }
        public Nullable<System.DateTime> deletedat { get; set; }
    }
}
